[tools]
atuin = "latest"
bat = "latest"
bitwarden = "latest"
chezmoi = "latest"
circleci = "latest"
direnv = "latest"
fnox = "latest"
java = "openjdk-21"
lsd = "latest"
starship = "latest"
zellij = "latest"
